# Generated by Django 4.0.3 on 2022-04-06 14:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('Location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('humidity', models.IntegerField()),
                ('Temperature', models.IntegerField()),
            ],
        ),
    ]
