# Generated by Django 4.0.3 on 2022-04-06 16:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='Location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
